# Generated by Django 5.1.4 on 2025-02-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_resume_name_award_certification_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='portfolio',
        ),
    ]
