# Generated by Django 5.1.4 on 2025-03-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionofresponsibility',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='PositionOfResponsibility',
        ),
    ]
