# Generated by Django 5.1.4 on 2025-03-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_positionofresponsibility_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency_level',
        ),
    ]
