# Generated by Django 5.1.4 on 2025-03-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_skill_proficiency_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='award',
            name='description',
        ),
    ]
